### ISSUE TITLE
使用角评功能的时候学生的别名无效

### ISSUE THREAD

**Issue by EvenSharper** [lgc-NB2Dev/nonebot-plugin-bawiki#27]
比如指令是 ba角评 体香，或者体操服优香，或者运动服优香，等等
返回结果是 没有找到该角色的角评，可能是学生名称错误或者插件还未收录该角色角评
但是指令是 ba羁绊 体香；或者ba学生图鉴 体香等其他功能
则可以正常返回体操服优香cg图鉴等等。
ba角评 没包人，或者ba角评 优香也可以正常返回普通优香角评。

**Comment by lgc2333** [comment]
数据源问题，已修复，使用cdn源的请等待cdn源刷新缓存

https://github.com/lgc2333/bawiki-data/commit/b837b13b99707f86c60d355c09c114b7a2219fe2
