### ISSUE TITLE
输出ba日程表 中文乱码

### ISSUE THREAD

**Issue by Chocominttt** [lgc-NB2Dev/nonebot-plugin-bawiki#28]
ubuntu20.04

![90043E04-F29F-48F2-8442-D9CC7ED866B8](https://user-images.githubusercontent.com/79995876/233878194-790538ca-9944-4b36-b3f6-b32322109479.jpeg)

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-akinator/issues/6

**Comment by Chocominttt** [comment]
> https://github.com/lgc-NB2Dev/nonebot-plugin-akinator/issues/6

已解决，谢谢🙏
