### ISSUE TITLE
ba语音不清晰

### ISSUE THREAD

**Issue by AirKeen76** [lgc-NB2Dev/nonebot-plugin-bawiki#30]
ba语音发出来听着不清晰，像是在电话里说的一样，就是音质有点差，和gamekee上的不一样

**Comment by lgc2333** [comment]
做个可选项用卡片发吧

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/releases/tag/v0.7.9
