### ISSUE TITLE
关于功能的建议（关卡攻略查询）

### ISSUE THREAD

**Issue by AirKeen76** [lgc-NB2Dev/nonebot-plugin-bawiki#31]
发送关卡名之后，自动在gamekee截图对应图文攻略并返回。
例如：
发送“攻略1-2”，则返回关卡1-2的图文攻略截图。
发送“攻略5-1”，则返回关卡5-1的图文攻略截图。
发送“攻略H6-1”，则返回关卡H6-1的图文攻略截图。
发送“攻略H13-3”，则返回关卡H13-3的图文攻略截图。

**Comment by lgc2333** [comment]
简单写了一下，将就用吧，如果有问题接着跟进就行，我是大懒狗

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/59048777/fa56e01f-5215-4256-b699-3d0d1a87aa30)
