### ISSUE TITLE
nb-cli没更新，安装之后是0.77版本的

### ISSUE THREAD

**Issue by AirKeen76** [lgc-NB2Dev/nonebot-plugin-bawiki#32]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/117345914/fff73091-cf21-4a34-8ead-8361bc23d36d)

**Comment by lgc2333** [comment]
`nb plugin update bawiki`

**Comment by lgc2333** [comment]
还不行就pip换官方源

**Comment by AirKeen76** [comment]
谢谢佬，pip换官方源就好了
