### ISSUE TITLE
关于BA_VOICE_USE_CARD

### ISSUE THREAD

**Issue by AirKeen76** [lgc-NB2Dev/nonebot-plugin-bawiki#33]
设置BA_VOICE_USE_CARD=True之后，在QQ发送语音指令，机器人就会没有任何报错直接关机，有什么头绪吗

**Comment by lgc2333** [comment]
？具体行为是？

**Comment by AirKeen76** [comment]
过程是这样![%9)MDW8`7Y{Q{KM6J}71UL](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/117345914/06b77082-bf60-402f-a7b2-b20495a88206)

**Comment by lgc2333** [comment]
原生nb没有问题，请咨询yunzai py-plugin作者
