### ISSUE TITLE
更新国际服千里眼all的图源

### ISSUE THREAD

**Issue by AirKeen76** [lgc-NB2Dev/nonebot-plugin-bawiki#34]
指令“千里眼 all”所使用的图源过于老旧，建议使用以下图源。并设置成每次使用指令时自动检查是否有更新。谢谢佬
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/117345914/f69ddf57-f330-41dd-a302-1c6d3087bb8a)

**Comment by lgc2333** [comment]
因为更新数据源千里眼图片的时候需要同时给该图片打上对应时间区间的坐标点：

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/59048777/44fc28c6-39c3-4daa-b8e2-188b0d99566f)

所以数据源千里眼图片更新的不够勤qaq

**Comment by lgc2333** [comment]
如果有意愿的话可以来数据源贡献一下（

https://github.com/lgc-NB2Dev/bawiki-data
