### ISSUE TITLE
"#arona 普拉娜"和"#arona plana"报错，其他的没问题

### ISSUE THREAD

**Issue by AirKeen76** [lgc-NB2Dev/nonebot-plugin-bawiki#35]
![QQ图片20230625223328](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/117345914/53f3f817-e8b0-486d-9c6a-682f534602b4)

**Comment by lgc2333** [comment]
看了一下gocq日志，原因是图片上传失败，估计是因为这张图片本身的原因导致发不出来了吧

这是获取到的图片，看下估计就清楚为什么发不出来了
![image](https://arona.cdn.diyigemt.com/image/some/plana.png)
