### ISSUE TITLE
报错 TypeError: __init__() got an unexpected keyword argument 'homepage'

### ISSUE THREAD

**Issue by Aobaaaa** [lgc-NB2Dev/nonebot-plugin-bawiki#36]
![SH3MTX$ PUJJ8H}MS(ODDUQ](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/106361074/d05c0895-d38f-454c-a325-71fd9228aad9)
装0.8.2出现报错，请问是什么问题

**Comment by lgc2333** [comment]
`pip install -U nonebot`
