### ISSUE TITLE
ba羁绊部分学生报错

### ISSUE THREAD

**Issue by A7424** [lgc-NB2Dev/nonebot-plugin-bawiki#37]
![PP9BCCM7SVXF`5}DI 35I~3](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/103619507/0014a4a9-a82e-4ec9-a94d-b06a9ea0f044)
ba羁绊 水泉报错，其他的没有问题

**Comment by A7424** [comment]
> ![PP9BCCM7SVXF`5}DI 35I~3](https://user-images.githubusercontent.com/103619507/258166095-0014a4a9-a82e-4ec9-a94d-b06a9ea0f044.png) ba羁绊 水泉报错，其他的没有问题

顺便问问nonebot_plugin_PicMenu是怎么安装的，是真没看见安装方法

**Comment by lgc2333** [comment]
> 顺便问问nonebot_plugin_PicMenu是怎么安装的，是真没看见安装方法

`nb plugin install nonebot-plugin-PicMenu`

**Comment by A7424** [comment]
> nb plugin install nonebot-plugin-PicMenu

尝试过，提示nonebot-plugin-PicMenu 未找到，还尝试过在src\plugins路径git clone 但是报错

**Comment by A7424** [comment]
> 这个可能是数据源问题，我有时间会看一眼的

好的

**Comment by lgc2333** [comment]
> 尝试过，提示nonebot-plugin-PicMenu 未找到，还尝试过在src\plugins路径git clone 但是报错

呃……不会没装进虚拟环境吧，尝试用虚拟环境的python执行一次pip install，windows下的示例：`.venv\Scripts\python.exe -m pip install nonebot-plugin-PicMenu`

**Comment by A7424** [comment]
> > 尝试过，提示nonebot-plugin-PicMenu 未找到，还尝试过在src\plugins路径git clone 但是报错
> 
> 呃……不会没装进虚拟环境吧，尝试用虚拟环境的python执行一次pip install，windows下的示例：`.venv\Scripts\python.exe -m pip install nonebot-plugin-PicMenu`

已解决，感谢

**Comment by A7424** [comment]
> 这个可能是数据源问题，我有时间会看一眼的

佬，顺带一提，日程表似乎也寄了，不知道是不是我的原因
![)8(WZYCI9)0INL5VGRSXP(H](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/103619507/23ca0d75-e934-48c1-9d3f-8e07ca5739ac)

**Comment by lgc2333** [comment]
可以复现，明天排查

**Comment by lgc2333** [comment]
可以复现，明天排查

**Comment by A7424** [comment]
> 可以复现，明天排查

辛苦了，泪目

**Comment by lgc2333** [comment]
> ba羁绊 水泉报错，其他的没有问题

抱歉，这个应该没法修，这是tx的锅了，把l2d图片风控了，我本地测试是没问题的，接到gocq上就寄了

可以做一下发送图片失败的提示

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/59048777/e9250b51-74ec-4ce5-8698-d89bcb293018)

**Comment by A7424** [comment]
> > ba羁绊 水泉报错，其他的没有问题
> 
> 抱歉，这个应该没法修，这是tx的锅了，把l2d图片风控了，我本地测试是没问题的，接到gocq上就寄了
> 
> 可以做一下发送图片失败的提示
> 
> ![image](https://user-images.githubusercontent.com/59048777/258336972-e9250b51-74ec-4ce5-8698-d89bcb293018.png)

哦哦，好的

**Comment by lgc2333** [comment]
> 佬，顺带一提，日程表似乎也寄了，不知道是不是我的原因 

可能是图片太大了，我分段发送吧

**Comment by lgc2333** [comment]
日程表已改成分页发送

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/59048777/1faadf4c-9fc3-469d-992f-49016ee7906b)
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/59048777/489c9b84-bb34-4c8c-8a07-3bedc0427657)

**Comment by A7424** [comment]
> 日程表已改成分页发送
> 
> ![image](https://user-images.githubusercontent.com/59048777/258368314-1faadf4c-9fc3-469d-992f-49016ee7906b.png) ![image](https://user-images.githubusercontent.com/59048777/258368359-489c9b84-bb34-4c8c-8a07-3bedc0427657.png)

好的
