### ISSUE TITLE
ba羁绊有反应，但是不出图

### ISSUE THREAD

**Issue by A7424** [lgc-NB2Dev/nonebot-plugin-bawiki#39]
![GI1)K47SQY$~`V_{R)P1HE](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/103619507/cc222c82-a0f0-4b42-a2fa-9a40d3828872)
如图，这是尝试重启后bot后的，重启前提示“l2d被风控，可能是因为太涩”以下是报错，第二张为重启前有文字但无图的报错
![HHSUOION$UQ$%U W 9@$AWS](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/103619507/04c1ff49-0ab1-49da-a763-20d95b78c7c3)

![K@V57TEX~ B{~1UC3E 84XS](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/103619507/7d69093a-bb3d-4402-a682-9ecbf84350fa)
插件版本为0.8.4，今天才发现之前竟然一直是0.7.7（

**Comment by lgc2333** [comment]
第一张是群聊学习的报错，请去向该插件反馈

关于发图报错，我会尽量排查下原因

**Comment by A7424** [comment]
> 第一张是群聊学习的报错，请去向该插件反馈
> 
> 关于发图报错，我会尽量排查下原因

哦哦，第一张图看错了，不好意思

**Comment by A7424** [comment]
> 第一张是群聊学习的报错，请去向该插件反馈
> 
> 关于发图报错，我会尽量排查下原因

刚刚重启又试了试，只有发不出图的会报错（l2d太涩的那个），有返回文字的后台则没有报错，只是不出图

**Comment by lgc2333** [comment]
related to https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/issues/45 , close
