### ISSUE TITLE
中文出现乱码

### ISSUE THREAD

**Issue by Lc113** [lgc-NB2Dev/nonebot-plugin-bawiki#40]
![1275259539-2573059985-BA0B0D4BD69F4D410685FB0992BED12E](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/62469261/d4157e63-a047-4991-9dbb-b070bfd3608f)
系统：CentOS 8
环境：美国IP属地，服务器
原因：系默认字体文件无中文

代码中是否有位置能够手动指定字体文件？

**Comment by lgc2333** [comment]
参考 https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/issues/28
不推荐手动指定字体

**Comment by Lc113** [comment]
已解决，感谢
