### ISSUE TITLE
ba千里眼截图异常

### ISSUE THREAD

**Issue by Lc113** [lgc-NB2Dev/nonebot-plugin-bawiki#42]
![1275259539-4072069527-077249A8B9E57022BD9AFBDE69882B5C](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/62469261/5492d4b9-71d8-480a-a887-c28b6d6c30d3)

效果如图
后台没有抛出任何报错

**Comment by lgc2333** [comment]
数据源问题吧，我有时间去打点
