### ISSUE TITLE
已解决：从SchaleDB返回的截图内容不为中文

### ISSUE THREAD

**Issue by Lc113** [lgc-NB2Dev/nonebot-plugin-bawiki#43]
### **问题：**
现有代码下
SchaleDB返回的截图（似乎）会因为服务器IP归属地而返回非中文内容
那总不能再往国内挂个代理吧...

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/62469261/1805b9c7-237a-4bfd-b1d0-7bf8a93d4388)

### **个人解决方案：**
schaledb.py顶部添加
`import pyppeteer`

在异步函数async def schale_get_stu_info(stu)内添加
```
await page.click("#ba-navbar-regionselector")
await page.click("#ba-navbar-languageselector")
await page.click("#ba-navbar-languageselector-cn")
await page.click("#ba-navbar-regionselector")
```

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/62469261/0ccbdf26-1e46-4923-88c6-d03744966652)

三个标签id分别对应
regionselector  设置按钮
languageselector 设置语言
languageselector-cn 选择中文

二次点击设置使其缩回

### **效果：**
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/62469261/001b0b3b-dc12-46e9-bf48-a7ca8fc21e84)

### **缺点：**
`pip install pyppeteer`

其实就这也不算啥特别大的缺点
问题是我昨天弄的时候装完这个之后
其他的插件会抛出No module named 'pyee.asyncio'的错误
还需要补上一个

`pip install playwright`

可能问题因机器而异吧
就怕整的不稳定了

对nonebot_plugin_htmlrender不是很了解
如果里面有更好的模拟点击方案，可以替换pyppeteer库

**或者有其他能保证返回中文的方法？**

**Comment by lgc2333** [comment]
太不优雅了，我选择改cookie或者执行js代码

**Comment by Lc113** [comment]
😭

**Comment by lgc2333** [comment]
尝试 0.9.0 版本
