### ISSUE TITLE
关于抽卡功能

### ISSUE THREAD

**Issue by PhantherG** [lgc-NB2Dev/nonebot-plugin-bawiki#44]
如果我不想自动补全常驻池角色应该怎么做

**Comment by lgc2333** [comment]
![-2b3699c322493536](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/59048777/3d42e88b-0c3b-4a29-b31f-561a1805e52a)

**Comment by PhantherG** [comment]
不是 我的意思是我自己手写了gacha.json但是一使用抽卡功能我自己手写的就被替换掉了 我不想那个文件被替换应该怎么做

**Comment by lgc2333** [comment]
重启bot

**Comment by PhantherG** [comment]
就是把gacha.json放进去再重启吗

**Comment by lgc2333** [comment]
你说的是哪个gacha.json，是数据源那个还是`data/BAWiki`里那个

**Comment by PhantherG** [comment]
data/BAWiKi里的

**Comment by lgc2333** [comment]
> data/BAWiKi里的

这个玩意好像是要用的时候才去读的，按理来说不应该被旧数据覆盖啊，你先试试看吧

**Comment by PhantherG** [comment]
![QQ图片20230830154724](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/117614023/1acf304e-0f96-4621-aad6-180db79deea9)

**Comment by lgc2333** [comment]
> 你说的是哪个 `gacha.json`，是数据源那个还是 `data/BAWiki` 里那个，**【这两个 `gacha.json` 内容和作用都不一样】**

如果想修改卡池内容，请去向[数据源](https://bawiki.lgc2333.top)贡献
