### ISSUE TITLE
api网站似乎已迁移

### ISSUE THREAD

**Issue by Ealvn** [lgc-NB2Dev/nonebot-plugin-bawiki#49]
主线攻略查询的这个网站, 好像已经迁移; 现在机器人查攻略时会超时
https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/blob/411d3d544182a1c1d1ef4f1157ca13dc28ad858d/nonebot_plugin_bawiki/config.py#L19

这一行的网址好像直接换成 https://tutorial.arona.diyigemt.com/ 就可以了

**Comment by lgc2333** [comment]
如果你改了之后没问题的话就直接pr过来吧
