### ISSUE TITLE
balogo错误信息太长

### ISSUE THREAD

**Issue by ws-work** [lgc-NB2Dev/nonebot-plugin-bawiki#50]
使用balogo时若发生错误，所有错误信息（包括历史错误）都会被bot回复给用户
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/88135140/ebd46622-def7-456e-8372-9c35d91f92f2)

**Comment by XieXiLin2** [comment]
需要更多信息，如:
- 您给 Bot 发送的指令消息内容是？
- 您的插件版本？
等等。
（想不到怎么去复现……）

**Comment by ws-work** [comment]
更新最新版本后没有这个问题了，是我草率提issue了万分抱歉
PS：原本在只输入一个参数是会出现这种错误
