### ISSUE TITLE
插件功能建议征集

### ISSUE THREAD

**Issue by lgc2333** [lgc-NB2Dev/nonebot-plugin-bawiki#8]
不知道接下来写点什么，问问大家意见吧qwq
直接在下面评论就行

**Comment by Rouphy** [comment]
加个模拟抽卡（）

**Comment by lgc2333** [comment]
> 加个模拟抽卡（）
已完成

**Comment by SunflowerYuuka** [comment]
请问模拟抽卡能不能加个cd呢？0v0

**Comment by lgc2333** [comment]
> 请问模拟抽卡能不能加个cd呢？0v0

已完成，顺便做了个给PicMenu自动填写字体路径配置的功能

**Comment by lgc2333** [comment]
issue先关掉吧，有什么建议直接发issue就行
